### PR TITLE
feat: css var support, closes #30

### LINKED ISSUE #30: Support css variables in the color option
In order to support light / dark mode, or different themes, it would be very helpful if the `colors` option supported CSS custom properties like this:

```
colors: ["var(--primary)", "var(--secondary)"]
```

Great work so far, thanks!

### PR DESCRIPTION
**Pull request by raae**
- feat: support for css variables
- demo: changes in demo to test css variables

### CODE REVIEW

**Comment by raae** [comment]
The solution lets you supply css variables in addition to hex colors. The css variables should still resolve to hex color though.

**Comment by bradgarropy** [comment]
Don't forget the `README` update!

**Comment by raae** [comment]
The colors are fetched on initial load, so will not change when dark/light is changes. If moved to the animationFrame it would change dynamically making "new snow" get the new colors.

**Comment by bradgarropy** [comment]
Ah I see what you're saying. Then `animationFrame` would definitely be the better option so that a transition would occur eventually.

I think there is still some friction because `canvas-confetti` wants actual color codes. I wonder if `canvas` can draw with `css` variables. But I understand that `canvas-confetti` is not your library.

**Comment by raae** [comment]
🎉 Moved it into animationFrame, red flakes will appear in dark mode and then disappear again when changing to light mode, demo https://letitsnow-featcssvarsupportcloses30.gtsb.io/.

**Pull request merged**
